version: '3.7'
services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
        - ./db:/var/lib/mysql
        - "/etc/timezone:/etc/timezone:ro"
        - "/etc/localtime:/etc/localtime:ro"
    environment:
        MYSQL_ROOT_PASSWORD: $MYSQL_ADMIN_PASSWORD
        TZ: $TZ

  bluecherry:
    container_name: bluecherry
    restart: unless-stopped
    volumes:
      - /media/bluecherry:/var/lib/bluecherry/recordings
#######################################################
# Enable this only if you have a supported VAAPI device and /dev/dri exists on the host system.
#    devices:
#      - /dev/dri:/dev/dri
#######################################################
    ports:
        - "7001:7001"
        - "7002:7002"
    depends_on:
        - mysql

networks:
    default:
        name: bluecherry_net
